import type { Metadata } from 'next';
import { ToolPageFooterBand } from '@/components/tools/ToolPageShell';
import ToolSEOContent, {
  SEOSection, SEOProse, HowItWorks, UseCases, FAQ, RelatedTools,
} from '@/components/tools/ToolSEOContent';
import HarToCurlClient from './client';

const canonicalUrl = 'https://unblockdevs.com/har-to-curl';

export const metadata: Metadata = {
  title: 'HAR to cURL Converter — Extract cURL Commands from HAR Files | UnblockDevs',
  description: 'Convert HAR files to cURL commands instantly. Extract curl commands from any HAR file, replay browser requests in your terminal, mask secrets. 100% client-side HAR file parser.',
  keywords: [
    'har to curl converter',
    'convert har file to curl',
    'extract curl commands from har',
    'har file parser',
    'har to curl',
    'har file converter',
    'network request to curl',
    'browser request to curl',
    'copy as curl online',
    'har to python',
    'har to code',
    'har timeline',
    'har debug',
    'api request from har',
    'replay har requests',
    'har batch convert',
    'chrome har to curl',
    'firefox har to curl',
    'devtools har export',
  ],
  openGraph: {
    title: 'HAR to cURL Converter | UnblockDevs',
    description: 'Convert HAR files to cURL and multiple languages. Clean headers, mask secrets, timeline, batch script. 100% client-side.',
    type: 'website',
    url: canonicalUrl,
    images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'UnblockDevs - Free Developer Tools Suite' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HAR to cURL Converter | UnblockDevs',
    description: 'Convert HAR files to cURL and multiple languages. Clean headers, mask secrets. 100% client-side.',
  },
  alternates: { canonical: canonicalUrl },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'HAR to cURL Converter',
  url: canonicalUrl,
  description: 'Convert HAR files to cURL commands and multiple programming languages. All processing is 100% client-side.',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Any',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  featureList: [
    'Convert HAR to cURL commands',
    'Multi-request extraction from a single HAR file',
    'Secret masking for Authorization headers and cookies',
    'Request timeline visualisation',
    'Batch cURL script export',
    'Convert to Python, Go, Java, PHP, Ruby',
    '100% client-side — HAR files never leave your device',
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.9',
    ratingCount: '1900',
    bestRating: '5',
  },
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is a HAR file?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A HAR (HTTP Archive) file is a JSON-formatted log of all network requests and responses captured by a browser. It includes URLs, HTTP methods, request and response headers, cookies, request bodies, response status codes, and timing data. HAR files are generated by browser developer tools and are the standard way to export recorded network activity.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I convert a HAR file to cURL?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Export a HAR file from your browser DevTools (Network tab → right-click → Save as HAR), then paste or upload it into this tool. The converter extracts every request and generates a ready-to-run cURL command for each one, preserving all headers, cookies, and request bodies.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I export a HAR file from Chrome?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Open Chrome DevTools (F12), go to the Network tab, reload the page or trigger the requests you want to capture, then right-click anywhere in the request list and choose "Save all as HAR with content". You can then upload the .har file or paste its JSON content directly into this converter.',
      },
    },
    {
      '@type': 'Question',
      name: 'What can you do with cURL commands extracted from HAR?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'cURL commands extracted from a HAR file let you replay exact browser requests from the terminal without a browser. You can reproduce bugs locally, share reproducible API calls with teammates, run requests in CI pipelines, debug authentication flows, use them as inputs for API testing tools like Postman or k6, or convert them to Python, Go, or other languages for scripting.',
      },
    },
  ],
};

export default function HarToCurl() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <HarToCurlClient />

      <ToolSEOContent>
        {/* What */}
        <SEOSection id="what" heading="What Is a HAR File?">
          <SEOProse>
            A <strong>HAR (HTTP Archive)</strong> file is a JSON-formatted log of every network request
            and response a browser makes during a session. When you open DevTools and record network
            activity, all of that data — URLs, methods, request headers, cookies, bodies, response
            status codes, and timing — can be saved as a single <code>.har</code> file.
          </SEOProse>
          <SEOProse>
            HAR is a standard format supported by Chrome, Firefox, Safari, and Edge. It is the most
            complete snapshot of browser-to-server communication available, making it ideal for sharing
            reproducible bug reports, debugging authentication flows, auditing what a page actually
            sends, and converting browser interactions into scripts you can run anywhere.
          </SEOProse>
        </SEOSection>

        {/* How it works */}
        <SEOSection id="how" eyebrow="How it works" heading="Convert HAR to cURL in Seconds">
          <HowItWorks steps={[
            { n: '01', title: 'Export HAR from browser DevTools', desc: 'Open the Network tab, record your requests, then right-click and choose "Save all as HAR with content" in Chrome/Edge or "Save All As HAR" in Firefox.' },
            { n: '02', title: 'Paste or upload the HAR file', desc: 'Drag and drop the .har file or paste the raw HAR JSON directly into the converter. The tool parses all requests instantly.' },
            { n: '03', title: 'Review requests', desc: 'Browse the list of extracted requests, filter by URL or method, and optionally mask Authorization headers and cookies for safe sharing.' },
            { n: '04', title: 'Copy cURL commands', desc: 'Copy individual cURL commands, export a batch shell script, or convert to Python, Go, Java, PHP, or Ruby code.' },
          ]} />
        </SEOSection>

        {/* Use cases */}
        <SEOSection id="uses" eyebrow="Use cases" heading="When Developers Convert HAR to cURL">
          <UseCases cases={[
            { icon: '🐛', title: 'Reproduce Bugs Locally', desc: 'Capture the exact failing request in a browser session and replay it from the terminal without needing a browser or UI.' },
            { icon: '🤝', title: 'Share API Calls with Team', desc: 'Send teammates a self-contained cURL command that reproduces an issue — no environment setup required.' },
            { icon: '⚙️', title: 'Automate Requests in CI', desc: 'Turn HAR captures into shell scripts or code to drive integration tests or load tests in automated pipelines.' },
            { icon: '🔐', title: 'Debug Auth Flows', desc: 'Inspect the exact Authorization headers, tokens, and cookies sent during a login or OAuth flow to diagnose auth failures.' },
            { icon: '🧪', title: 'API Testing', desc: 'Feed generated cURL commands into Postman, Insomnia, k6, or other API testing tools as a starting point for test suites.' },
            { icon: '🔍', title: 'Reverse Engineering', desc: 'Understand what requests a third-party page or app makes so you can replicate the same calls in your own code.' },
          ]} />
        </SEOSection>

        {/* How to export HAR */}
        <SEOSection id="export" heading="How to Export a HAR File from Your Browser">
          <SEOProse>
            All major browsers support HAR export from the Network panel in DevTools. Here is how to do
            it in each browser:
          </SEOProse>
          <SEOProse>
            <strong>Chrome and Edge:</strong> Open DevTools with <code>F12</code> or right-click →
            Inspect. Go to the <strong>Network</strong> tab. Reload the page or perform the actions that
            generate the requests you want to capture. Once the requests appear, right-click anywhere in
            the request list and choose <strong>Save all as HAR with content</strong>. Save the{' '}
            <code>.har</code> file, then upload it here or paste its JSON content.
          </SEOProse>
          <SEOProse>
            <strong>Firefox:</strong> Open Developer Tools with <code>F12</code>. Go to the{' '}
            <strong>Network</strong> tab. Trigger the requests you want to capture, then right-click in
            the request list and select <strong>Save All As HAR</strong>. Use the downloaded file with
            this converter.
          </SEOProse>
          <SEOProse>
            <strong>Safari:</strong> Enable the Develop menu under Preferences → Advanced → Show Develop
            menu. Open <strong>Develop → Show Web Inspector</strong> and go to the{' '}
            <strong>Network</strong> tab. After recording, use the export button to save as HAR, or
            right-click an individual request and choose <strong>Copy as cURL</strong> for single
            requests. You can also paste HAR JSON exported from Safari directly into this tool.
          </SEOProse>
        </SEOSection>

        {/* FAQ */}
        <SEOSection id="faq" eyebrow="FAQ" heading="Frequently Asked Questions">
          <FAQ items={[
            {
              q: 'What is a HAR file?',
              a: 'A HAR (HTTP Archive) file is a JSON log of all network requests and responses recorded by a browser. It contains URLs, HTTP methods, headers, cookies, request bodies, response codes, and timing data — everything shown in the browser DevTools Network tab, saved to a file.',
            },
            {
              q: 'How do I convert a HAR file to cURL?',
              a: 'Export a HAR file from your browser DevTools (Network tab → right-click → Save as HAR), then paste or upload it into this tool. The converter extracts every request and generates a ready-to-run cURL command for each one.',
            },
            {
              q: 'How do I export a HAR file from Chrome?',
              a: 'Open Chrome DevTools (F12), go to the Network tab, record the requests, then right-click in the request list and choose "Save all as HAR with content". Upload the .har file or paste its JSON content here.',
            },
            {
              q: 'What can I do with cURL commands extracted from a HAR?',
              a: 'You can replay requests in the terminal, share reproducible bug reports, run them in CI pipelines, use them in API testing tools like Postman or k6, or convert them to Python, Go, or other languages for scripting.',
            },
            {
              q: 'Is my HAR file sent to a server?',
              a: 'No. All processing happens entirely in your browser. Your HAR file — which may contain auth tokens, cookies, and other sensitive data — never leaves your device.',
            },
          ]} />
        </SEOSection>

        {/* Related tools */}
        <SEOSection id="related" eyebrow="Related tools" heading="Tools You Might Also Need">
          <RelatedTools tools={[
            { href: '/jwt-decoder', label: 'JWT Decoder', desc: 'Decode and inspect JWT tokens found in HAR Authorization headers', icon: '🪙' },
            { href: '/token-comparator', label: 'Token Comparator', desc: 'Compare two auth tokens to spot differences in claims', icon: '🔀' },
            { href: '/hash-generator', label: 'Hash Generator', desc: 'Hash request payloads for integrity checks', icon: '🔑' },
            { href: '/base64-encoder', label: 'Base64 Encoder', desc: 'Decode Base64-encoded values found in HAR headers or bodies', icon: '🔤' },
          ]} />
        </SEOSection>
      </ToolSEOContent>

      <ToolPageFooterBand toolName="har_to_curl" />
    </>
  );
}
