import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://unblockdevs.com'
  const currentDate = new Date().toISOString().split('T')[0]

  // All blog posts
  const blogPosts = [
    'physical-ai-edge-computing-complete-guide',
    'physical-ai-autonomous-vehicles-complete-guide',
    'physical-ai-systems-complete-guide',
    'digital-provenance-complete-guide',
    'domain-specific-language-models-complete-guide',
    'multiagent-systems-complete-guide',
    'ai-security-platforms-complete-guide',
    'ai-supercomputing-platforms-complete-guide',
    'ai-native-development-platforms-complete-guide',
    'how-to-invest-consistently-usa-tech-stocks',
    'high-impact-tech-stocks-investment-guide',
    'xbox-game-pass-games-complete-guide',
    'git-commands-cheat-sheet-tips-tricks',
    'git-complete-guide-what-why-how-when',
    'ces-2026-fire-tv-stick-4k-max-project-ava',
    'token-security-privacy-best-practices',
    'token-technologies-history-evolution',
    'tokens-complete-guide',
    'mysql-json-complete-guide',
    'mysql-25-most-used-queries',
    'mysql-10-most-used-functions',
    'must-learn-tech-skills-2030',
    'most-useful-tech-skills-2026',
    'notebooklm-cheat-sheet-tips',
    'notebooklm-complete-guide',
    'ai-prompt-engineering-guide',
    'cursor-ai-code-editor-guide',
    'ai-tools-developers-guide',
    'ai-productivity-tools-complete-guide',
    'chatgpt-real-life-usage-guide',
    'apache-kafka-complete-guide',
    'apache-kafka-applications',
    'apache-kafka-cheat-sheet',
    'ai-native-platforms-complete-guide',
    'agentic-ai-complete-guide',
    'physical-ai-complete-guide',
    'confidential-computing-complete-guide',
    '5g-6g-complete-guide',
    'blockchain-complete-guide',
    'digital-twins-complete-guide',
    'json-stringify-vs-json-parse-difference',
    'json-stringify-complete-guide',
    'how-to-get-curl-from-chrome',
    'har-to-curl-converter-complete-guide',
    'copy-as-curl-from-browser-guide',
    'how-to-convert-har-files-to-curl',
    'curl-vs-python-requests-comparison',
    'curl-to-python-requests-complete-guide',
    'json-schema-generator-tutorial',
    '25-broken-json-examples-fix',
    'why-json-breaks-in-real-world-apis',
    'invalid-json-vs-valid-json-examples',
    'how-to-fix-broken-json-without-understanding',
    'top-10-json-errors-waste-developer-time',
    'how-json-fixers-work-internally',
    'common-json-mistakes-fix-guide',
    'curl-to-code-converter-2026',
    'debug-api-changes-compare-responses',
    'free-mock-api-generator-guide',
    'best-free-developer-tools-2026',
    'html-tags-explained-guide',
    'advanced-html5-apis-guide',
    'api-payload-size-optimization',
    'api-response-comparator-testing-guide',
    'complete-guide-json-viewer-parser-beautifier',
    'css-explained-guide',
    'curl-to-code-converter-guide',
    'html-interview-questions',
    'json-api-design-patterns',
    'json-best-practices-production-guide',
    'json-format-standards-complete-guide',
    'json-schema-generator-validation-guide',
    'json-to-excel-converter-best-practices',
    'mysql-comma-separated-id-list-guide',
    'seo-optimized-html-markup',
    'structured-log-analysis-tools',
    'instagram-password-reset-email-guide',
    'nintendo-switch-online-gamecube-games',
    'low-code-ai-development-prompt-chunker',
    'how-to-change-whatsapp-number-without-losing-chats',
    'how-to-change-phone-number-telegram-without-notifying',
    'how-to-change-email-address-google-account-safely',
    'how-to-change-instagram-phone-number-email-2026',
    'how-to-change-apple-id-phone-number-without-losing-data',
    'how-to-cancel-audible-subscription-mobile-desktop',
    'how-to-cancel-netflix-subscription-without-losing-watch-history',
    'how-to-cancel-amazon-prime-membership-instantly',
    'how-to-cancel-spotify-premium-and-get-refund',
    'how-to-see-instagram-story-without-being-seen',
    'how-to-hide-online-status-on-whatsapp',
    'how-to-know-if-someone-blocked-you-on-instagram',
    'how-to-change-whatsapp-privacy-settings-maximum-security',
    'how-to-read-whatsapp-messages-without-blue-ticks',
    'how-to-see-deleted-instagram-messages-without-third-party-apps',
    'how-to-fix-cors-policy-error-javascript',
    'fix-json-parse-error-unexpected-token',
    'how-to-fix-module-not-found-error-nodejs',
    'fix-python-keyerror-explained-examples',
    'how-to-fix-nullpointerexception-java-beginner-friendly',
    'how-to-convert-curl-command-to-javascript-fetch',
    'how-to-read-json-file-python-3-ways',
    'how-to-validate-json-schema-javascript',
    'how-to-convert-json-to-csv-python',
    'how-to-parse-nested-json-java',
    'fix-access-control-allow-origin-missing-header-error',
    'why-json-stringify-returns-undefined-fix',
    'fix-cannot-read-property-map-of-undefined-javascript',
    'how-to-convert-curl-to-fetch-axios-automatically',
    'fix-unexpected-end-of-json-input-error-explained',
    'how-to-validate-api-response-using-json-schema',
    'why-my-api-works-in-postman-but-not-in-browser',
    'fix-maximum-call-stack-size-exceeded-javascript',
    'fix-unexpected-token-less-than-in-json-api-returns-html',
    'why-my-api-returns-200-ok-but-data-is-empty',
    'fix-failed-to-fetch-error-javascript-cors-https-network',
    'fix-cannot-read-properties-of-undefined-reading-length-javascript',
    'why-async-await-is-not-working-javascript-common-mistakes',
    'fix-uncaught-in-promise-error-javascript-explained',
    'fix-error-listen-eaddrinuse-nodejs-port-already-in-use',
    'why-process-env-is-undefined-nodejs-and-how-to-fix-it',
    'fix-hydration-failed-error-nextjs-server-vs-client-mismatch',
    'how-to-debug-javascript-errors-using-browser-devtools',
    'common-http-status-codes-every-developer-should-understand',
    'how-to-handle-api-rate-limits-gracefully-in-production',
    'why-my-code-works-locally-but-fails-on-submission-common-reasons',
    'how-to-read-error-messages-properly-as-beginner-programmer',
    'how-to-debug-code-step-by-step-beginner-friendly-guide',
    'what-is-time-complexity-explained-with-simple-examples',
    'what-is-stack-vs-queue-explained-with-real-life-examples',
    'binary-search-explained-like-youre-5-with-code-example',
    'what-is-recursion-explained-with-simple-real-life-examples',
    'what-is-hashmap-hashtable-explained-simply-with-examples',
    'what-is-two-pointer-technique-explained-for-beginners',
    'what-is-sliding-window-technique-explained-with-simple-examples',
    'what-is-linked-list-singly-vs-doubly-explained-simply',
    'what-is-bfs-vs-dfs-differences-explained-with-examples',
    'prefix-sum-technique-explained-simply',
    'merge-sort-explained-step-by-step-why-preferred-in-interviews',
    'greedy-algorithm-explained-with-simple-examples',
  ]

  // Main pages
  const mainPages = [
    {
      url: '',
      priority: 1.0,
      changefreq: 'daily' as const,
    },
    {
      url: 'json-beautifier',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'blog',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'about',
      priority: 0.7,
      changefreq: 'monthly' as const,
    },
    {
      url: 'contact',
      priority: 0.6,
      changefreq: 'monthly' as const,
    },
    {
      url: 'privacy-policy',
      priority: 0.5,
      changefreq: 'monthly' as const,
    },
    {
      url: 'terms',
      priority: 0.5,
      changefreq: 'monthly' as const,
    },
    {
      url: 'disclaimer',
      priority: 0.5,
      changefreq: 'monthly' as const,
    },
    // SEO landing pages - Error fix pages
    {
      url: 'fix-unexpected-end-of-json-input',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'fix-unexpected-token-in-json',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'fix-unexpected-token-less-than-json',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'fix-expected-comma-or-brace-json',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'fix-invalid-control-character-json',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'fix-json-parse-error-javascript',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    // Tool landing pages
    {
      url: 'how-to-fix-broken-json-online',
      priority: 0.8,
      changefreq: 'weekly' as const,
    },
    {
      url: 'json-fixer-online',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'json-validator',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'json-formatter',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'curl-to-requests',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'json-schema-generation',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'convert-curl-to-http-request',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'curl-to-python-requests',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'json-stringify-online',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'prompt-chunker',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'token-comparator',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
    {
      url: 'lander',
      priority: 0.6,
      changefreq: 'monthly' as const,
    },
    {
      url: 'har-to-curl',
      priority: 0.9,
      changefreq: 'weekly' as const,
    },
  ]

  // Generate sitemap entries
  const entries: MetadataRoute.Sitemap = [
    // Main pages
    ...mainPages.map((page) => ({
      url: `${baseUrl}/${page.url}`,
      lastModified: currentDate,
      changeFrequency: page.changefreq,
      priority: page.priority,
    })),
    // Blog posts
    ...blogPosts.map((slug) => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified: currentDate,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
  ]

  return entries
}

